[project]
name = "quizzie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "rich>=13.9.4",
    "ruff>=0.8.2",
]
